### PR TITLE
OE-Managers

### PR DESCRIPTION
**Pull request by ousamasama**
## Link to Ticket
[Issue #13](https://github.com/talkative-tangs/Bangazon-API/issues/13)

## Description of Proposed Changes

-Reorganized our file structure.
-Added Semantic-UI
-Added React Router
-Added API Managers
-Added "Home" Page
-Added Customers List
-Setup Promise and Initial State
-More that I can't think of.

## Steps to Test

-Make sure to NPM Install from Banagazon-React top directory.
-Begin at localhost:3000/home with your django server set to 8000.
-Click on Ecommerce.
-Click on Customers List.
-Ensure list of customers is available.

```sh
git fetch --all
git checkout oe-managers

```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Components
* Managers
* App.Js
* Index.Js
* More

## Mentions @username

@robbyhecht  
@BryanNilsen
@laboyd001

### CODE REVIEW

**Comment by laboyd001** [comment]
🦆 
i pulled down your branch
I'm able to see the new nav links
I can see a list of customers

**Comment by BryanNilsen** [comment]
I pulled down your branch, ran the npm install, and navigated to localhost:3000/home
I clicked on ecommerce and customer list and could see the list of customers as expected.
Looks good.
👍 👍

**Comment by laboyd001** [comment]
🦆 
looks good

**Review by robbyhecht — APPROVED** [review]
cool beans

**Pull request merged**
